ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    sensor_timeout: 0.1

    # ✅ ใช้ IMU
    imu0: "/imu/data"
    imu0_config: [false, false, false,  # ไม่ใช้ x, y, z
                  false, false, true,     # ใช้มุม yaw, pitch, roll
                  false, false, false,  # ไม่ใช้ความเร็วเชิงเส้น x, y, z
                  false, false, true,     # ใช้ความเร็วเชิงมุม
                  false, false, false]  # ไม่ใช้ความเร่ง


    odom0: "/odom"
    odom0_config: [true, true, false,  # ❌ ไม่ใช้ position.x, position.y
                  false, false, false,  # ❌ ไม่ใช้ orientation
                  true,  false, false,  # ✅ ใช้ linear velocity x
                  false, false, false,   # ✅ ใช้ angular velocity z
                  false, false, false]  # ❌ ไม่ใช้ linear acceleration

    # ✅ ให้ EKF คำนวณ Orientation จาก Angular Velocity
    imu0_differential: true
    odom0_differential: true
    imu0_remove_gravitational_acceleration: false

    # ✅ ตั้งค่า TF Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # ✅ ให้ EKF บรอดแคสต์ TF `odom → base_link`
    publish_tf: true
    print_diagnostics: true

